### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by gmantele** [ivoa-std/ADQL#12]
A `.gitignore` file so that ignoring files generated by the execution of `make pdf html` (especially the PDF and HTML files).

Running the Makefile also touches the `ivoatex/` directory (apparently, just the metadata). I also propose to update `.gitmodules` so that ignoring this "dirty" state.

**Comment by olebole** [comment]
This is probably a matter of taste. However, I would usually prefer not to have a `.gitignore` file. There was some [discussion on slack about this](https://ivoa.slack.com/archives/CB596HLAK/p1557400828016000).
IMO, it makes the handling less transparent, since f.e. with a `git status` you can't see anymore whether the directory is clean or not. Also, `git clean` also ignores the files listed in `.gitignore`, not really creating a clean directory.
Especially as an "external" user of a repository, I often run into difficulties there.

**Comment by gmantele** [comment]
I see indeed some discussions on this topic. I personally agree with Tim Jenness.

I like `.gitignore` files for two reasons:

1. thanks to this file, `git status` gives a clear view of what commited content has changed and what new content can be added ; the listing is not polluated by generated/temporary content.
2. whoever wants to commit anything, we have a guarantee that no file generated by ivoatex's Makefile will be commited (and then pushed) by accident. So, no PDF, HTML or DOC has a risk to be inside the repository (again, by accident).

Personally, I always check the diff of all files before commiting anything. But I know that some people really likes `git commit -a`, or just commit everything quickly. In such case, we might be in situations where PDF are in GitHub repositories.

I never use `git clean` because I prefer to not rely too much on automatic/"smart" utilities for such sensitive things (e.g. removing files). But I also agree with Tim, `git clean -x` seems to be what you want if you want to ignore rules of the `.gitignore` file.

Finally, and just for clarification, I would not put inside this `.gitignore` file the custom/user files. My aim is to list only the files generated by the ivoatex's Makefile.

**Comment by olebole** [comment]
This goes a bit off-topic, but I would rather try to teach people not to use `git commit -a` (or even `git commit -a -m "latest changes"`, but to carefully think about the commit. On Volute, there are sometimes log entries like "new commit" or "new version", which don't really help to understand the history, and commits which seem to revert what was just committed. On Github, we have merge requests and before merging contributors can be asked to correct the commit(s), to correct the log, remove unintended changes etc.

**Comment by gmantele** [comment]
I agree, that should indeed be like that in an ideal world.

But in the real world, reviewers and contributors are humans, and thus, errors may/will happen. So, I prefer to minimise the risks, when possible. A `.gitignore` file is really not much to pay for a higher guarantee not to spoil the repository history with commit**s** like `remove pdf` if a Pull Request review went too fast (which may also happen, by accident/lazyness, in case of large Pull Requests). This will also prevent reviewer to be more efficient reviewing the real content of a request instead of loosing time checking for generated files.

**Comment by Zarquan** [comment]
I think in the Slack discussion we left it up to the choice of the editor for now.

**Comment by gmantele** [comment]
_Solved in Pull Request #13 (approved and merged)_
