### ISSUE TITLE
" Invalid ADQL regular identifier" when != operator used

### ISSUE THREAD

**Issue by almicol** [ivoa-std/ADQL#38]
The legitimate query:
SELECT mycol FROM mytab WHERE mycol!='toto'

returns the error:
```Invalid ADQL regular identifier: : "mycol!"! If it aims to be a column/table name/alias, you should write it between double quotes.```

**Comment by gmantele** [comment]
I think this issue is in the wrong GitHub project :S
The problem is not in the ADQL standard but in VOLLT/ADQL-Lib. So, I copied this issue in there: https://github.com/gmantele/vollt/issues/121

**Comment by almicol** [comment]
Oops, thanks and sorry Gregory!

I hope all is well with you and your dears,
Alberto
