### ISSUE TITLE
Add a note about case folding of identifiers

### ISSUE THREAD

**Issue by gmantele** [ivoa-std/ADQL#47]
With different implementations of ADQL/TAP come different behaviours regarding the case folding of table/column identifiers.

For instance, let's take a column named `ra`. In different implementations, it could be defined with a different case. Multiple reasons could lead to a such situation: different DBMS, different service implementers choice, different ADQL parser, ... Because of that, the theoretically same ADQL query may not work in all these implementations. In one ADQL service the following will work:

```sql
SELECT ra
FROM a_great_table
```

...but will not in the second unless the column identifier is written with a different case and between double quotes:

```sql
SELECT "Ra"
FROM a_great_table
```

Besides, some ADQL parsers will consider that a non-delimited column (or, generally speaking, an identifier) will match an existing column whatever case it is written in. Other parsers will not. _Note that all have to preserve the case when the identifier is delimited (i.e. put between double quotes)._

Because of such differences in the processing of case folding when specifying identifiers (i.e. columns, tables, schemas), some users can easily be confused. However, this situation is really hard to fix as most implementations depend on DBMS that already have different behaviours regarding case folding of identifiers.

In order to make ADQL users aware of this but also to make ADQL implementers more careful on their choice of identifiers, a note should be added in the ADQL standard document.

One suggestion raised by @msdemlei on the DAL mailing list ([8th Dec. 2020 - "TAP, ADQL and field names inconsistencies between providers."](http://mail.ivoa.net/pipermail/dal/2020-December/008395.html)) is:

> a word of advice:
> avoid mixed-case names in ADQL databases; they become trouble as soon
> as people start gratuitously adding quotes to identifiers, which at
> least a certain demography is likely to do

**Comment by msdemlei** [comment]
On Mon, Jan 25, 2021 at 06:30:46AM -0800, Grégory Mantelet wrote:
> Because of that, the theoretically same ADQL query may not work in
> all these implementations. In one ADQL service the following will
> work:
> 
> ```sql
> SELECT ra
> FROM a_great_table
> ```
> 
> ...but will not in the second unless the column identifier is
> written with a different case and between double quotes:
> 
> ```sql
> SELECT "Ra"
> FROM a_great_table

For the record, bugs and standards violations aside, that is not
really a property of services but of the table schema.

> Besides, some ADQL parsers will consider that a non-delimited
> column (or, generally speaking, an identifier) will match an
> existing column whatever case it is written in. Other parsers will
> not. _Note that all have to preserve the case when the identifier

Me, I'd say our implicit policy of "whenever we don't say anything,
SQL92 applies" makes it clear that the common SQL rules apply,
meaning 'ra' cannot match a column named '"Ra"' ever.

As pointed out in the mail thread Grégory references, it's a bit
trickier with 'ra' vs. '"RA"' or '"ra"', and actual implementations
deviate from SQL92 there.  For, instance for Postgres
https://www.postgresql.org/docs/13/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
states:

  The folding of unquoted names to lower case in PostgreSQL is
  incompatible with the SQL standard, which says that unquoted names
  should be folded to upper case. Thus, foo should be equivalent to
  "FOO" not "foo" according to the standard.

While in practice, this apparently hasn't bitten us much, I'd still
say that in 2.2 we ought to commit to a specific folding rule; as we
need to think hard what that means for the underlying databases, I
suspect that's too much effort for 2.1.

Given all this, I stand by my recommendation to add some text
discouraging the use of delimited identifiers in ADQL-queriable
tables, although...

> > a word of advice:
> > avoid mixed-case names in ADQL databases; they become trouble as soon
> > as people start gratuitously adding quotes to identifiers, which at
> > least a certain demography is likely to do

...that particular text perhaps sounds a bit too much like a blog
post.

What about adding, perhaps in 2.1.7:

  Data providers should avoid defining column names using delimited
  identifiers, as, when these are mixed-case or are not written in
  the default case (uppercase by SQL92, lower case in most modern
  RDBMSes), users must use delimited identifiers as well.  This, in
  turn, may lead to interoperabilitiy problems between services
  offering the same table, or to failing backwards compatiblity when
  moving between backend RDBMSes.
