### ISSUE TITLE
Check ModelInstanceInVot keywords are consistent with ADQL

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ADQL#54]
The ModelInstanceInVot project are using keywords like `FILTER`, `GROUP_BY`, `JOIN`, `PRIMARYKEY` and `FOREIGNKEY` to link data between tables. 

This is a heads-up to the ADQL team to be aware of these and check that the way that ModelInstanceInVot are using these keywords is consistent with the existing definitions in ADQL and DAL.  

See ModelInstanceInVot issues [3](https://github.com/ivoa-std/ModelInstanceInVot/issues/3), [6](https://github.com/ivoa-std/ModelInstanceInVot/issues/6), [11](https://github.com/ivoa-std/ModelInstanceInVot/issues/11) and [12](https://github.com/ivoa-std/ModelInstanceInVot/issues/12)

**Comment by gmantele** [comment]
_Discussion on [ModelInstanceInVot#12](https://github.com/ivoa-std/ModelInstanceInVot/issues/12)_

**Comment by gmantele** [comment]
> _Discussion on [ModelInstanceInVot#12](https://github.com/ivoa-std/ModelInstanceInVot/issues/12)_

Discussion closed there. So, let's close it here as well.
