### ISSUE TITLE
Clarify core/extended funcationality comment

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/ADQL#56]
The second paragraph of Sec 1 "Introduction" says:
> The ADQL specification makes no distinction between core and advanced or extended functionalities.

But this seems to be contradicted by other parts of the standard, e.g. the presence of section 4 "Optional components" and the comment in section 1.2 "Extended functionality":
> This document defines the minimum set of functions, operators and datatypes that a service MUST implement in order to register as a service that implements this version of the ADQL specification.

Is the second paragraph of the introduction a relic of earlier versions that ought to be reworded or removed?  Or have I misunderstood its intent?

**Comment by gmantele** [comment]
I think it is indeed a relic of the previous version where there was no optional feature. In my mind, there should be a distinction between the extended functionnalities made by the service using ADQL, and the core features (which may be optional considering this new version) of the ADQL. I think that was the original intent of this part of the document, but I can understand how confusing it could be for an ADQL newbie.

So, all the sections you mention may be all a little reworded to clearly make this distinction understandable.

**Comment by gmantele** [comment]
@mbtaylor , does my proposition of correction in the PullRequest #66 looks better to you?

**Comment by mbtaylor** [comment]
Yes, thank you.  Reviewed and approved.
