### ISSUE TITLE
Broken HTML doc references

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/ADQL#60]
At least some of the document cross-references in the HTML formatted version of the document are broken, e.g. [sec 3.5.2 of PR-ADQL-2.1-20210528.html](https://www.ivoa.net/documents/ADQL/20210528/PR-ADQL-2.1-20210528.html#tth_sEc3.5.2) reads:
> The CIRCLE datatype maps to the corresponding type defined in the . 

In the [PDF rendering](https://www.ivoa.net/documents/ADQL/20210528/PR-ADQL-2.1-20210528.pdf) it correctly says:
> The CIRCLE datatype maps to the corresponding type defined in the DALI specification.

**Comment by gmantele** [comment]
Very good eyes ;-)

I used the Makefile of ivoatex to publish the whole thing on the IVOA Documents page. I've also tried locally with `make html` et I got the same result.

I've to admit I have no clue how it works and what went wrong here. Maybe @msdemlei would have some idea here 0:-)

**Comment by msdemlei** [comment]
On Thu, Jul 01, 2021 at 10:30:10AM -0700, Grégory Mantelet wrote:
> I used the Makefile of ivoatex to publish the whole thing on the IVOA Documents page. I've also tried locally with `make html` et I got the same result.
> 
> I've to admit I have no clue how it works and what went wrong here. Maybe @msdemlei would have some idea here 0:-)

Well, this is a problem explained in
http://mail.ivoa.net/pipermail/dal/2018-January/007942.html (a bit
down, look for ivoa-cite); in short: tth can't cope with all the
trickery that Dave put into ivoa-cite.tex.

I've fixed that back then, still in volute, which is now commit
db4a0fc08fa4892ba9e6e5c644451b088a358a8d (from Jan 2018).  But then
Dave reverted that change in a8b83493165e9f1973b35a04e18b20843747049f
(November 2018).  Not sure why he did that -- @zarquan?

Me, I'd guess the 2018 fixes would still work, so I'd first try
cherry-picking db4a0fc08fa4892ba9e6e5c644451b088a358a8d out of the
history.
