### ISSUE TITLE
README Proposed Rec link out of date

### ISSUE THREAD

**Issue by tsdower** [ivoa-std/ADQL#62]
The "Proposed Recommendation" link in Readme is to an old(2018) version of the document, which can lead to some confusion on review.

Should this be changed to load the May 2021 'final for real' version, the auto PDF preview _DRAFT_ version, or removed? I have no strong opinions.

**Comment by gmantele** [comment]
Yes, you're right. I was aware of that, but I was not sure this link was used and I thought it could wait for the next REC...thanks to you, I know now some people are using it :D So, I guess I have to update it now. Thank you for the reminder ;)

**Comment by tsdower** [comment]
I don't think it's urgent! But I figured it was better to say something than forget and maybe have the wrong one show up in final :)
