### ISSUE TITLE
More concise change log possible from 2.0 to 2.1?

### ISSUE THREAD

**Issue by tomdonaldson** [ivoa-std/ADQL#64]
Version 2.0 was approved back in 2008, so it's not surprising Appendix C (changes from previous version) has accumulated a lot of content, and that content does help to understand the evolution of the document.

However, for the purposes of review, it might be really helpful to have a new section at the top of Appendix C that captures the significant net differences between 2.0 and 2.1.  Maybe that wouldn't shorten the list enough to matter, but I'm hoping that squashing the list into summaries (and removing interim versioning and history) would help make reviews easier.

**Comment by gmantele** [comment]
You're right. This section is now quite messy. There are a lot of of features that have been introduced then removed and introduced again. I think it should be enough to be less detailed now we are reaching soon a REC. I'll try to clean up this list. I don't think it is necessary to make another section ; cleaning up (mostly squashing lot of items) should be enough.

**Comment by tomdonaldson** [comment]
That sounds great, thanks!
