### ISSUE TITLE
Box search has strange behaviour - astroquery/gaiaquery

### ISSUE THREAD

**Issue by user29A** [ivoa-std/ADQL#70]
We’ve noticed that if you query a circle, it produces sources that occupy an actual circular area on the sky independent of how close one is to the poles – you get sources within a radius of the field center.

However, if you query for a BOX (i.e. a square), and specify a side-length, then if you are near the poles it gives the proper sweep in declination, but the width of the box is determined not by width in degrees on the sky, but width in right ascension, which will be much narrower near the poles than an actual span of degrees on the sky.

How would we get similar behaviour as the circle query but for a box query? For circular-aperture images we always used circle because the field actually is a circle, but now testing with square images we’ve noticed that if the image is near a pole, the BOX query does not actually return a square as the image sees, but a square in terms of RA & Dec, which is then just a narrow strip through the middle of what the telescope actually records if near a pole. 

We would expect that a BOX search behaves the same as a CIRCLE search, in terms of area of actual sky requested, not area in terms of RA & Dec.

We have been directed to the ADQL source by both astroquery and gaiaquery groups.

We can provide more detailed info if required. Please see the attached figures. The circle query is requested with a given radius, and the box query is requested with the same side length equivalent to the circle, i.e. a side-length two-times the circle radius.

![box query](https://user-images.githubusercontent.com/40668405/171288312-06deb4d8-189e-46a8-b990-0d904aea9db9.jpg)
![circle query](https://user-images.githubusercontent.com/40668405/171288314-13882bbf-8700-4133-baaa-a93bf04e4d5e.jpg)

**Comment by msdemlei** [comment]
On Tue, May 31, 2022 at 02:36:55PM -0700, user29A wrote:
> However, if you query for a BOX (i.e. a square), and specify a
> side-length, then if you are near the poles it gives the proper
> sweep in declination, but the width of the box is determined not by
> width in degrees on the sky, but width in right ascension, which
> will be much narrower near the poles than an actual span of degrees
> on the sky.

ADQL 2.0 refers to STC 1.33 as to the semantics of Box, and now that
you mention it I have to say it doesn't really say there whether the
size is to be interpreted in the tangential plane (i.e. divide the RA
range by cos(δ) for some reasonable choice of δ) or as a coordinate
interval.  I think one could argue both ways.

The upshot here is that the behaviour you describe is rather
certainly standards-compliant, and I think it is what most ADQL
implementations do in practice.

But BOX hasn't been a good idea anyway; it doesn't make anyone happy,
neither you not those that wanted a coordinate interval (which it
definitely is not, as it is bounded by great circles).  We are hence
deprecating it in ADQL 2.1, and it would be wise to not build
anything on it.

From what you write, it seems you are trying to fetch objects that
might be visible on an image; if that is your use case and you really
cannot live with the extra objects you get when doing a query against
a circle, I suppose the best you can do now is compute the
coordinates of the four corners (or, as necessary, additional points
in between) of that image and make a polygon out of these.

**Comment by user29A** [comment]
Yes, you have understood the concern correctly. 

The application is for retrieving objects from a catalogue given an area of sky that a detector is imaging; some detectors have circular apertures and so the CIRCLE query produces the result one would expect; however most detectors image square areas of sky, not great circles or intervals in RA, and so one might expect that a BOX query behaves the same way that a CIRCLE query does, but the shape is just a square. And so, yes, specifying the corners of the image as a polygon would be the solution here, since BOX doesn't actually return a square.

The specific application is for an automated world coordinate solver, which requires that the objects retrieved from a catalogue are correspondent with the objects imaged on the sky. The pointing of a telescope is never perfect anyway, and so there are always extraneous objects around the edges between the catalogue retrieval and the image, but it helps if these can be limited. A circle inside a square is likely the safest approach, but then one might miss out on objects in the corners (between the square and the circle) which might have been useful for the solver to know about.

We will try out the polygon query.

Thanks for the response.

**Comment by user29A** [comment]
Perhaps you could implement a SQUARE query (as opposed to BOX) where the square performs as has been discussed. 

CIRCLE must be internally computing a polygon anyway, is it not? Perhaps that could be done for SQUARE too?

Cheers.

**Comment by msdemlei** [comment]
On Wed, Jun 01, 2022 at 09:05:47AM -0700, user29A wrote:
> Perhaps you could implement a SQUARE query (as opposed to BOX)
> where the square performs as has been discussed. 

This would be "whatever a TAN projection would work out to"?  I give
you that might make a few applications somewhat simpler, but one
would need support for this kind of thing in the underlying database
systems, and one would have to figure out what should turn up in the
result table when someone writes

  SELECT SQUARE(....) AS my_area FROM ...

-- which would probably mean a new xtype in DALI, too.  In short: it
would make data providers' lives a significant deal harder for what I
think is a minor convenience (over computing a polygon client-side),
and hence I'd be surprised if someone were to start to make it happen
(which is how these things work in the IVOA: someone starts working
on it).

> CIRCLE must be internally computing a polygon anyway, is it not?

No -- circles are *a lot* simpler than anything else, in particular
polygons.  Checking for "distance<radius" is straightforward.
Computing whether a sequence of great circle segments winds around a
point an even (outside) or odd (insize) number of times is...
challenging.

**Comment by user29A** [comment]
Yes...then there's image rotation, too, which would mean that a "SQUARE" query would still have non-correspondence of sources around the corners.  A circle is obviously invariant with respect to image field rotation relative to sky coordinates...a query gets you the sources in the circle regardless. But if your image is a square, and is rotated relative to sky coordinates, then the catalogue retrieval and the image sources will have non-correspondence around the corners. Without knowing the field rotation in the first place, which you won't without a WCS already solved, which you don't have yet, then you can't actually calculate the polygon for the field either.

Well, that's it then. Square does no better than circle when the field rotation is arbitrary (which is our case), and, you can't actually compute the polygon coordinates without the WCS, which you don't have before solving it anyway.

CIRCLE it is. BOX or "square" never made any sense for me to use in the first place.

And yes, I can see why the BOX logic is as it is now, given the complexity involved and getting into winding, etc.

Thanks for your time.

**Comment by gmantele** [comment]
Thanks to both of you for this discussion . This indeed confirms that `BOX` should definitely not be in ADQL any more.
